webinars/panorama-ssot/nautobot_ssot_panorama/urls.py
"""Plugin URLS."""
from django.urls import path
from nautobot.core.views.routers import NautobotUIViewSetRouter
from nautobot.extras.views import ObjectChangeLogView, ObjectNotesView

from nautobot_ssot_panorama.views import (
    VirtualSystemUIViewSet,
    LogicalGroupUIViewSet,
    ControlPlaneSystemUIViewSet,
    DeviceVirtualSystemTabView,
    DeviceLogicalGroupTabView,
)
from nautobot_ssot_panorama.models import VirtualSystem, LogicalGroup, ControlPlaneSystem

router = NautobotUIViewSetRouter()
router.register("virtual-system", VirtualSystemUIViewSet)
router.register("control-plane-system", ControlPlaneSystemUIViewSet)
router.register("logical-group", LogicalGroupUIViewSet)
urlpatterns = [
    path(
        "control-plane-system/<uuid:pk>/changelog/",
        ObjectChangeLogView.as_view(),
        name="controlplanesystem_changelog",
        kwargs={"model": ControlPlaneSystem},
    ),
    path(
        "control-plane-system/<uuid:pk>/notes/",
        ObjectNotesView.as_view(),
        name="controlplanesystem_notes",
        kwargs={"model": ControlPlaneSystem},
    ),
    path(
        "virtual-system/<uuid:pk>/changelog/",
        ObjectChangeLogView.as_view(),
        name="virtualsystem_changelog",
        kwargs={"model": VirtualSystem},
    ),
    path(
        "virtual-system/<uuid:pk>/notes/",
        ObjectNotesView.as_view(),
        name="virtualsystem_notes",
        kwargs={"model": VirtualSystem},
    ),
    path(
        "virtual-system/<uuid:pk>/device/",
        DeviceVirtualSystemTabView.as_view(),
        name="virtualsystem_device_tab",
    ),
    path(
        "logical-group/<uuid:pk>/changelog/",
        ObjectChangeLogView.as_view(),
        name="logicalgroup_changelog",
        kwargs={"model": LogicalGroup},
    ),
    path(
        "logical-group/<uuid:pk>/notes/",
        ObjectNotesView.as_view(),
        name="logicalgroup_notes",
        kwargs={"model": LogicalGroup},
    ),
    path(
        "logical-group/<uuid:pk>/device/",
        DeviceLogicalGroupTabView.as_view(),
        name="logicalgroup_device_tab",
    ),
]
urlpatterns += router.urls

webinars/panorama-ssot/nautobot_ssot_panorama/models.py
"""Models extending the Firewall plugin."""
from django.db import models
from django.urls import reverse
from nautobot.core.models import BaseModel
from nautobot.core.models.generics import PrimaryModel
from nautobot.extras.utils import extras_features
from nautobot.utilities.tree_queries import TreeManager
from tree_queries.models import TreeNode


@extras_features(
    "custom_fields",
    "custom_links",
    "custom_validators",
    "export_templates",
    "graphql",
    "relationships",
    "statuses",
    "webhooks",
)
class ControlPlaneSystem(PrimaryModel):  # pylint: disable=too-many-ancestors
    """Models Palo Alto Panorama."""

    name = models.CharField(max_length=100)
    device = models.OneToOneField(to="dcim.Device", null=True, related_name="panorama", on_delete=models.CASCADE)
    verify_ssl = models.BooleanField(default=True, verbose_name="Verify SSL")
    port = models.PositiveSmallIntegerField(default=443)
    fqdn_or_ip = models.CharField(max_length=100, verbose_name="FQDN/IP")
    secrets_group = models.ForeignKey(
        to="extras.SecretsGroup",
        on_delete=models.SET_NULL,
        default=None,
        blank=True,
        null=True,
        verbose_name="Secrets Group (API user/pass)",
    )

    class Meta:
        """Meta class."""

        ordering = ["name"]
        verbose_name = "Control Plane System"
        verbose_name_plural = "Control Plane Systems"

    def get_absolute_url(self):
        """Return detail view URL."""
        return reverse("plugins:nautobot_ssot_panorama:controlplanesystem", args=[self.pk])

    def __str__(self):
        """Stringify instance."""
        return self.name


@extras_features(
    "custom_fields",
    "custom_links",
    "custom_validators",
    "export_templates",
    "graphql",
    "relationships",
    "statuses",
    "webhooks",
)
class VirtualSystem(PrimaryModel):  # pylint: disable=too-many-ancestors
    """Models Palo Alto VSYS."""

    system_id = models.PositiveSmallIntegerField()
    name = models.CharField(max_length=48)
    device = models.ForeignKey(to="dcim.Device", related_name="vsys", on_delete=models.CASCADE)
    interfaces = models.ManyToManyField(
        to="dcim.Interface", related_name="assigned_vsys", through="VirtualSystemAssociation"
    )

    class Meta:
        """Meta class."""

        ordering = ["name"]
        verbose_name = "Virtual System"
        verbose_name_plural = "Virtual Systems"

    def get_absolute_url(self):
        """Return detail view URL."""
        return reverse("plugins:nautobot_ssot_panorama:virtualsystem", args=[self.pk])

    def __str__(self):
        """Stringify instance."""
        return self.name


class VirtualSystemAssociation(BaseModel):
    """Enforce an interface is not assigned more than once."""

    vsys = models.ForeignKey("nautobot_ssot_panorama.VirtualSystem", on_delete=models.CASCADE)
    iface = models.OneToOneField("dcim.Interface", on_delete=models.CASCADE)


@extras_features(
    "custom_fields",
    "custom_links",
    "custom_validators",
    "export_templates",
    "graphql",
    "relationships",
    "statuses",
    "webhooks",
)
class LogicalGroup(TreeNode, PrimaryModel):  # pylint: disable=too-many-ancestors
    """Logical grouping of Devices & VirtualSystems."""

    name = models.CharField(max_length=48)
    devices = models.ManyToManyField(to="dcim.Device", related_name="logical_group", through="LogicalGroupToDevice")
    virtual_systems = models.ManyToManyField(
        to="nautobot_ssot_panorama.VirtualSystem", related_name="logical_group", through="LogicalGroupToVirtualSystem"
    )
    control_plane = models.ForeignKey(
        to="nautobot_ssot_panorama.ControlPlaneSystem",
        null=True,
        blank=True,
        related_name="logical_groups",
        on_delete=models.CASCADE,
    )
    pre_policy = models.ForeignKey(
        to="nautobot_firewall_models.Policy",
        null=True,
        blank=True,
        related_name="pre_policy",
        on_delete=models.SET_NULL,
    )
    post_policy = models.ForeignKey(
        to="nautobot_firewall_models.Policy",
        null=True,
        blank=True,
        related_name="post_policy",
        on_delete=models.SET_NULL,
    )

    objects = TreeManager()

    class Meta:
        """Meta class."""

        ordering = ["name"]
        verbose_name = "Logical Group"
        verbose_name_plural = "Logical Groups"

    def get_absolute_url(self):
        """Return detail view URL."""
        return reverse("plugins:nautobot_ssot_panorama:logicalgroup", args=[self.pk])

    def __str__(self):
        """Stringify instance."""
        return self.name


class LogicalGroupToDevice(BaseModel):
    """Enforce a Device is not assigned more than once."""

    group = models.ForeignKey("nautobot_ssot_panorama.LogicalGroup", on_delete=models.CASCADE)
    device = models.OneToOneField("dcim.Device", on_delete=models.CASCADE)


class LogicalGroupToVirtualSystem(BaseModel):
    """Enforce a VirtualSystem is not assigned more than once."""

    group = models.ForeignKey("nautobot_ssot_panorama.LogicalGroup", on_delete=models.CASCADE)
    vsys = models.OneToOneField("nautobot_ssot_panorama.VirtualSystem", on_delete=models.CASCADE)

webinars/panorama-ssot/nautobot_ssot_panorama/templates/nautobot_ssot_panorama/controlplanesystem_retrieve.html
{% extends 'generic/object_detail.html' %}
{% load helpers %}

{% block content_left_page %}
    <div class="panel panel-default">
        <div class="panel-heading">
            <strong>Control Plane System</strong>
        </div>
        <table class="table table-hover panel-body attr-table">
            <tr><td>FQDN/IP</td><td>{{ object.fqdn_or_ip }}</td></tr>
            <tr><td>Verify SSL</td><td>{{ object.verify_ssl|render_boolean }}</td></tr>
            <tr><td>Port</td><td>{{ object.port }}</td></tr>
            <tr><td>Device</td><td>{% if object.device %}<a href="{{ object.device.get_absolute_url }}">{{ object.device.name }}</a>{% else %}{{ None|placeholder}}{% endif %}</td></tr>
            <tr><td>Secrets Group</td><td><a href="{{ object.secrets_group.get_absolute_url }}">{{ object.secrets_group.name }}</a></td></tr>
        </table>
    </div>
{% endblock %}

webinars/panorama-ssot/nautobot_ssot_panorama/templates/nautobot_ssot_panorama/device_logical_groups.html
{% extends 'dcim/device.html' %}
{% load tree_helpers %}

{% block content %}
    <div class="row">
        <div class="col-md-6">
            <div class="panel panel-default">
                <div class="panel-heading"><strong>Logical Group</strong></div>
                <table class="table table-hover table-headings">
                    <tr>
                        <th>Name</th>
                        <th>Relationship</th>
                    </tr>
                    {% for group in object.logical_group.first.ancestors %}
                        <tr>
                            <td>{{ group.ancestors.count|tree_position|safe }}<a href="{{ group.get_absolute_url }}">{{ group.name }}</a></td>
                            <td>Ancestor</td>
                        </tr>
                    {% endfor %}
                    <tr>
                        {% if object.logical_group.exists %}
                            <td>{{ object.logical_group.first.ancestors.count|tree_position|safe }}<a href="{{ object.logical_group.first.get_absolute_url }}">{{ object.logical_group.first.name }}</a></td>
                            <td>Directly Assigned</td>
                        {% else %}
                            <td><span class="text-muted">Not Assigned To A Logical Group</span></td>
                            <td><span class="text-muted">—</span></td>
                        {% endif %}
                    </tr>
                </table>
            </div>
        </div>
        <div class="col-md-6"></div>
    </div>
{% endblock content %}

webinars/panorama-ssot/nautobot_ssot_panorama/templates/nautobot_ssot_panorama/device_virtual_systems.html
{% extends 'dcim/device.html' %}

{% block content %}
    <div class="row">
        <div class="col-md-6">
            <div class="panel panel-default">
                <div class="panel-heading"><strong>Virtual Systems</strong></div>
                <table class="table table-hover table-headings">
                    <tr>
                        <th>System ID</th>
                        <th>Name</th>
                        <th>Interface</th>
                        <th>Logical Group</th>
                    </tr>
                    {% for vsys in object.vsys.all|dictsort:"system_id" %}
                        <tr>
                            <td>{{ vsys.system_id }}</td>
                            <td><a href="{{ vsys.get_absolute_url }}">{{ vsys.name }}</a></td>
                            <td>
                                {% for iface in vsys.interfaces.all %}
                                    <i class="mdi mdi-ethernet"></i><a href="{{ iface.get_absolute_url }}">{{ iface.name }}</a><br/>
                                {% endfor %}
                            </td>
                            <td>
                                {% if vsys.logical_group.exists %}<a href="{{ vsys.logical_group.first.get_absolute_url }}">{{ vsys.logical_group.first.name }}</a>{% else %}<span class="text-muted">—</span>{% endif %}
                            </td>
                        </tr>
                    {% endfor %}
                </table>
            </div>
        </div>
        <div class="col-md-5"></div>
        <div class="col-md-1">
            {% if perms.dcim.change_device and perms.nautobot_ssot_panorama.add_virtualsystem %}
                <a href="{% url 'plugins:nautobot_ssot_panorama:virtualsystem_add' %}?device={{ object.id }}" class="btn btn-primary" id="add-button">
                    <span class="mdi mdi-plus-thick" aria-hidden="true"></span> Add Virtual System
                </a>
            {% endif %}
        </div>
    </div>
{% endblock content %}